# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[30,)" #mandatory (32 is current forge version)

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU GPLv3"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Rohzek/InfiniOres/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="infiniores" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName="InfiniOres" #mandatory

# A text field displayed in the mod UI
authors="Rohzek" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A simple mod make ore nodes that deplete and regenerate.
Come talk to be about it at: https://discord.gg/JyPwFzu
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.infiniores]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[30,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
	
# Here's another dependency
[[dependencies.infiniores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
